blank_issues_enabled: true
contact_links:
    - name: ðŸ“š Documentation
      url: https://learn.umh.app
      about: Please check our documentation before opening an issue.
    - name: Discord
      url: https://discord.com/invite/F9mqkZnm9d
      about: Join our Discord server to get help from our community.
